#!/usr/bin/env python3
"""Apply the Sonnet membership audit (review/out_*.json) to produce the cleaned
taxonomy + labels.json.

Per verdict: keep -> member stays in its class; evict with a valid `suggest`
(a vocab label) -> reassigned there; evict with unknown/null -> dropped;
drop_class -> the whole label is removed (members fall through to their suggest).
Then support is recomputed and a floor selects the trained classes.

    python data/relabel/apply_review.py [--min-svgs 15] [--min-libs 2] [--write]

Writes data/relabel/concept_labels.clean.jsonl + labels.preview.json always;
config/labels.json only with --write.
"""
from __future__ import annotations
import argparse, json
from collections import defaultdict
from pathlib import Path

LAB = Path(__file__).resolve().parent.parent.parent
INV = LAB / "data" / "relabel" / "inventory.jsonl"
REVIEW = LAB / "data" / "relabel" / "review"
CLEAN = LAB / "data" / "relabel" / "concept_labels.clean.jsonl"
PREVIEW = LAB / "data" / "relabel" / "labels.preview.json"
CONTRACT = LAB / "config" / "labels.json"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-svgs", type=int, default=15)
    ap.add_argument("--min-libs", type=int, default=2)
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    inv = {json.loads(l)["key"]: json.loads(l) for l in INV.open()}
    vocab = set(json.loads((REVIEW / "index.json").read_text())["vocab"])

    dropped_classes = set()
    key_label: dict[str, str] = {}
    n_keep = n_reassign = n_drop = 0
    for of in sorted(REVIEW.glob("out_*.json")):
        d = json.loads(of.read_text())
        for c in d.get("classes", []):
            label = c["label"]
            if c.get("drop_class"):
                dropped_classes.add(label)
            for m in c.get("members", []):
                key = m["key"]
                if c.get("drop_class") or not m.get("keep", False):
                    sug = m.get("suggest")
                    if sug and sug != "unknown" and sug in vocab and sug not in dropped_classes:
                        key_label[key] = sug; n_reassign += 1
                    else:
                        n_drop += 1   # -> unknown / not a class member
                else:
                    key_label[key] = label; n_keep += 1
    # a class dropped AFTER some member was reassigned into it: prune
    key_label = {k: v for k, v in key_label.items() if v not in dropped_classes}

    groups: dict[str, dict] = defaultdict(lambda: {"keys": [], "n": 0, "libs": set()})
    for key, label in key_label.items():
        r = inv.get(key)
        if not r:
            continue
        g = groups[label]
        g["keys"].append(key); g["n"] += r["n_svgs"]; g["libs"].update(r["libs"])

    kept = [(lab, g) for lab, g in groups.items()
            if g["n"] >= args.min_svgs and len(g["libs"]) >= args.min_libs]
    kept.sort(key=lambda kv: (-kv[1]["n"], kv[0]))

    # --- report ---
    print(f"verdicts: kept={n_keep} reassigned={n_reassign} dropped={n_drop}  "
          f"junk-classes-dropped={len(dropped_classes)}")
    if dropped_classes:
        print("  dropped class labels:", sorted(dropped_classes))
    total = sum(g["n"] for _, g in kept)
    print(f"\nCLEANED taxonomy @ floor(>={args.min_svgs} svgs, >={args.min_libs} libs): "
          f"{len(kept)} classes, {total} svgs ({100*total/sum(r['n_svgs'] for r in inv.values()):.1f}% of corpus)")
    print("distribution at other floors:")
    for ms in [10, 15, 20, 25, 30, 40, 50]:
        n = sum(1 for _, g in groups.items() if g["n"] >= ms and len(g["libs"]) >= args.min_libs)
        sv = sum(g["n"] for _, g in groups.items() if g["n"] >= ms and len(g["libs"]) >= args.min_libs)
        print(f"   >={ms:>3} svgs / >={args.min_libs} libs: {n:>4} classes, {sv:>6} svgs, ~{sv/max(n,1)*0.6*6:.0f} train ex/class")

    print("\n-- 30 largest CLEANED classes (label | svgs | libs | members) --")
    for lab, g in kept[:30]:
        mem = sorted(g["keys"], key=lambda k: -inv[k]["n_svgs"])[:7]
        print(f"  {lab:16s} {g['n']:4d} {len(g['libs'])}lib  {mem}")

    # --- write cleaned map + labels.json ---
    with CLEAN.open("w") as fh:
        for k, v in sorted(key_label.items()):
            fh.write(json.dumps({"key": k, "label": v}) + "\n")

    def write_doc(path: Path):
        labels = []
        for i, (lab, g) in enumerate(kept):
            labels.append({"index": i, "name": lab, "display": lab.replace("_", " "),
                           "synonyms": sorted(k for k in g["keys"] if k != lab)})
        path.write_text(json.dumps({
            "$comment": f"Generated by relabel pipeline (gemma4 relabel -> Sonnet audit). "
                        f"floor>={args.min_svgs}svgs/>={args.min_libs}libs. index=model output column.",
            "version": 1,
            "unknown": {"label": "unknown", "explicit_class": False,
                        "default_threshold": 0.5},
            "labels": labels}, indent=2))

    write_doc(PREVIEW)
    print(f"\n[apply_review] {len(kept)} classes -> {PREVIEW.relative_to(LAB)}; "
          f"clean map -> {CLEAN.relative_to(LAB)}")
    if args.write:
        write_doc(CONTRACT)
        print(f"[apply_review] WROTE CONTRACT -> {CONTRACT.relative_to(LAB)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
