#!/usr/bin/env python3
"""Turn the relabel map (concept_labels.jsonl) into a taxonomy and report the
POST-MERGE support distribution, so the trainable class set is chosen from real
numbers (not a guess). Each canonical label pools the SVGs of every concept_key
that maps to it; a support floor then decides which labels become trained classes.

    # report only (safe — writes a preview, never touches config/labels.json):
    python data/relabel/build_labels.py
    # with a chosen floor, and write the real contract:
    python data/relabel/build_labels.py --min-svgs 25 --min-libs 2 --write

Outputs data/relabel/labels.preview.json always; config/labels.json only with --write.
"""
from __future__ import annotations
import argparse, json
from collections import defaultdict
from pathlib import Path

LAB = Path(__file__).resolve().parent.parent.parent
INV = LAB / "data" / "relabel" / "inventory.jsonl"
LABELS = LAB / "data" / "relabel" / "concept_labels.jsonl"
CANON = LAB / "data" / "relabel" / "label_canonical.json"   # optional consolidation map
PREVIEW = LAB / "data" / "relabel" / "labels.preview.json"
CONTRACT = LAB / "config" / "labels.json"


def load() -> dict[str, dict]:
    inv = {json.loads(l)["key"]: json.loads(l) for l in INV.open()}
    lab = {json.loads(l)["key"]: json.loads(l)["label"] for l in LABELS.open()}
    canon = json.loads(CANON.read_text()) if CANON.exists() else {}
    groups: dict[str, dict] = defaultdict(lambda: {"keys": [], "n_svgs": 0, "libs": set()})
    for key, raw_label in lab.items():
        if key not in inv:
            continue
        label = canon.get(raw_label, raw_label)
        g = groups[label]
        g["keys"].append(key)
        g["n_svgs"] += inv[key]["n_svgs"]
        g["libs"].update(inv[key]["libs"])
    return groups


def report(groups: dict[str, dict]) -> None:
    total_svgs = sum(g["n_svgs"] for g in groups.values())
    print(f"\n=== POST-MERGE: {len(groups)} distinct labels, {total_svgs} svgs ===")
    print(f"{'floor (min svgs)':>16} {'min libs':>9} {'#classes':>9} {'svgs kept':>10} {'coverage':>9} {'~train ex/cls*':>14}")
    for ms in [10, 15, 20, 25, 30, 40, 50, 75]:
        for ml in [1, 2, 3]:
            kept = [g for g in groups.values() if g["n_svgs"] >= ms and len(g["libs"]) >= ml]
            if not kept:
                continue
            svgs = sum(g["n_svgs"] for g in kept)
            avg = svgs / len(kept)
            print(f"{ms:>16} {ml:>9} {len(kept):>9} {svgs:>10} {100*svgs/total_svgs:>8.1f}% {avg*0.6*6:>14.0f}")
        print()
    print("* avg source svgs/class x 0.6 train split x 6 augment copies")
    # show the biggest merged classes
    top = sorted(groups.items(), key=lambda kv: -kv[1]["n_svgs"])[:25]
    print("\n-- 25 largest merged labels (label | svgs | libs | #keys | sample keys) --")
    for label, g in top:
        ex = sorted(g["keys"], key=len)[:5]
        print(f"  {label:18s} {g['n_svgs']:4d}svgs {len(g['libs'])}libs {len(g['keys']):3d}keys  {ex}")


def write_labels(groups: dict[str, dict], min_svgs: int, min_libs: int, path: Path) -> int:
    kept = [(lab, g) for lab, g in groups.items()
            if g["n_svgs"] >= min_svgs and len(g["libs"]) >= min_libs]
    kept.sort(key=lambda kv: (-kv[1]["n_svgs"], kv[0]))
    labels = []
    for i, (label, g) in enumerate(kept):
        syns = sorted(k for k in g["keys"] if k != label)
        labels.append({"index": i, "name": label, "display": label.replace("_", " "),
                       "synonyms": syns})
    doc = {
        "$comment": "Generated by data/relabel/build_labels.py from the gemma4 concept relabel "
                    f"(floor: >={min_svgs} svgs, >={min_libs} libs). Index=model output column. "
                    "synonyms=concept_keys that pool into this label.",
        "version": 1,
        "unknown": {"label": "unknown", "explicit_class": False,
                    "$comment": "Abstain below default_threshold (tuned later from risk-coverage).",
                    "default_threshold": 0.5},
        "labels": labels,
    }
    path.write_text(json.dumps(doc, indent=2))
    return len(labels)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-svgs", type=int, default=25)
    ap.add_argument("--min-libs", type=int, default=2)
    ap.add_argument("--write", action="store_true", help="also write config/labels.json (the extension contract)")
    args = ap.parse_args()

    groups = load()
    report(groups)
    n = write_labels(groups, args.min_svgs, args.min_libs, PREVIEW)
    print(f"\n[build_labels] preview @ floor(>={args.min_svgs} svgs, >={args.min_libs} libs): "
          f"{n} classes -> {PREVIEW.relative_to(LAB)}")
    if args.write:
        n = write_labels(groups, args.min_svgs, args.min_libs, CONTRACT)
        print(f"[build_labels] WROTE CONTRACT: {n} classes -> {CONTRACT.relative_to(LAB)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
